### ISSUE TITLE
Can we just build with linaro toolchain

### ISSUE THREAD

**Issue by asypost** [MiyooCFW/kernel#1]
Hi,I'm trying to compile the kernel with **gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi**,but it seems that then generated **zImage** can't boot my bittboy v3.5,Is there something wrong?

**Comment by nisrulz** [comment]
@asypost how did you compile the kernel? I want to do so myself now, but I can't find the details on how to do it.

My reason to compile it is because of the other issue I am facing https://github.com/TriForceX/MiyooCFW/issues/316

When I clone this repo, I get the below repo (I am using macOS):

```
❯ git clone git@github.com:MiyooCFW/kernel.git
Cloning into 'kernel'...
remote: Enumerating objects: 65452, done.
remote: Counting objects: 100% (517/517), done.
remote: Compressing objects: 100% (441/441), done.
remote: Total 65452 (delta 56), reused 501 (delta 51), pack-reused 64935
Receiving objects: 100% (65452/65452), 173.55 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (5582/5582), done.
Updating files: 100% (61168/61168), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'include/uapi/linux/netfilter/xt_CONNMARK.h'
  'include/uapi/linux/netfilter/xt_connmark.h'
  'include/uapi/linux/netfilter/xt_DSCP.h'
  'include/uapi/linux/netfilter/xt_dscp.h'
  'include/uapi/linux/netfilter/xt_MARK.h'
  'include/uapi/linux/netfilter/xt_mark.h'
  'include/uapi/linux/netfilter/xt_RATEEST.h'
  'include/uapi/linux/netfilter/xt_rateest.h'
  'include/uapi/linux/netfilter/xt_TCPMSS.h'
  'include/uapi/linux/netfilter/xt_tcpmss.h'
  'include/uapi/linux/netfilter_ipv4/ipt_ECN.h'
  'include/uapi/linux/netfilter_ipv4/ipt_ecn.h'
  'include/uapi/linux/netfilter_ipv4/ipt_TTL.h'
  'include/uapi/linux/netfilter_ipv4/ipt_ttl.h'
  'include/uapi/linux/netfilter_ipv6/ip6t_HL.h'
  'include/uapi/linux/netfilter_ipv6/ip6t_hl.h'
  'net/netfilter/xt_DSCP.c'
  'net/netfilter/xt_dscp.c'
  'net/netfilter/xt_HL.c'
  'net/netfilter/xt_hl.c'
  'net/netfilter/xt_RATEEST.c'
  'net/netfilter/xt_rateest.c'
  'net/netfilter/xt_TCPMSS.c'
  'net/netfilter/xt_tcpmss.c'
```

My assumption is that this Kernel was built on Windows and I cannot do so on macOS??

**Comment by Rezzy-dev** [comment]
No, it was built on Linux, and it's interesting that you're getting this message on Mac OS (which is also Unix-based in arcitecture/design). To my best knowledge Mac OS supports case-sensitive filenaming. The hard disk partition that you're cloning the repo to, is it FAT formatted by any chance? Because FAT(32) does not support case-sensitive filenaming.

Make sure that the partition you're cloning to is a Mac (Mac OS Extended) or Linux (Ext) partition. See also:

https://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not#71360

**Comment by Rezzy-dev** [comment]
You can use VirtualBox or another VM software, installing Linux on it, or you can format a USB flash drive or SD card for the job (formatting the partition on it to be case-sensitive).

You can even create a live bootable version of Linux on a USB flash drive or SD card using UNetBootin for Mac, for example, and then boot the Mac into it by holding the Option key at boot time.
